[[redirects]]
  from = "/en/*"
  to = "https://uk-localise-test.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 301
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/fr/*"
  to = "https://fr-localise-test.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/fr/:splat"
  status = 301
  force = true 
  conditions = {Language = ["fr"]}






