[[redirects]]
  from = "/*"
  to = "https://uk-localise-test.netlify.app/:splat"
  status = 301
  force= true
  conditions = {Language = ["en"]}


[[redirects]]
  from = "/test"
  to = "https://uk-localise-test.netlify.app/:splat"
  status = 301
  force= true


[[redirects]]
  from = "/*"
  to = "https://fr-localise-test.netlify.app/:splat"
  status = 301
  force = true
  conditions = {Language = ["fr"]}