[[redirects]]
  from = "/en/*"
  to = "https://uk-localise-test.netlify.app/fr/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/_next/*"
  to = "https://fr-localise-test.netlify.app/en/_next/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/en/"
  status = 301
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/_next/*"
  to = "https://fr-localise-test.netlify.app/fr/_next/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/fr/*"
  to = "https://fr-localise-test.netlify.app/fr/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 301
  force = true 
  conditions = {Language = ["fr"]}






